// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: grade.proto

package grade

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for MaxClasses service

type MaxClassesService interface {
	//    rpc GetMaxClasses(GradeIdRequest) returns (GradeIdResponse) {}
	GetMaxClassesNew(ctx context.Context, in *GradeIdRequest, opts ...client.CallOption) (*GradeIdNewResponse, error)
}

type maxClassesService struct {
	c    client.Client
	name string
}

func NewMaxClassesService(name string, c client.Client) MaxClassesService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "maxclasses"
	}
	return &maxClassesService{
		c:    c,
		name: name,
	}
}

func (c *maxClassesService) GetMaxClassesNew(ctx context.Context, in *GradeIdRequest, opts ...client.CallOption) (*GradeIdNewResponse, error) {
	req := c.c.NewRequest(c.name, "MaxClasses.GetMaxClassesNew", in)
	out := new(GradeIdNewResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for MaxClasses service

type MaxClassesHandler interface {
	//    rpc GetMaxClasses(GradeIdRequest) returns (GradeIdResponse) {}
	GetMaxClassesNew(context.Context, *GradeIdRequest, *GradeIdNewResponse) error
}

func RegisterMaxClassesHandler(s server.Server, hdlr MaxClassesHandler, opts ...server.HandlerOption) error {
	type maxClasses interface {
		GetMaxClassesNew(ctx context.Context, in *GradeIdRequest, out *GradeIdNewResponse) error
	}
	type MaxClasses struct {
		maxClasses
	}
	h := &maxClassesHandler{hdlr}
	return s.Handle(s.NewHandler(&MaxClasses{h}, opts...))
}

type maxClassesHandler struct {
	MaxClassesHandler
}

func (h *maxClassesHandler) GetMaxClassesNew(ctx context.Context, in *GradeIdRequest, out *GradeIdNewResponse) error {
	return h.MaxClassesHandler.GetMaxClassesNew(ctx, in, out)
}
