registry:
  type: etcd
  addr: 10.52.26.3:22379
  ttl: 30s
  interval: 10s
client:
  pool_ttl: 10s
mysql:
  Addr: 10.52.26.3:3306
  User: root
  PasswdSecret: 1913a79dc77c0ef862711763368319e1
  DB: hackathon
serviceName: hackathon.controller.GetMaxClass
metrics:
  Port : 10109
  Name: hackathon.controller.GetMaxClass
  Tag: hackathon
consulAddr: 10.52.26.3:8500
